language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
sudo: enabled
addons:
  apt:
    update: true
install:
  - sudo apt-get update
  - sudo $TRAVIS_BUILD_DIR/deploy/travis/install.sh
# command to run tests
script:
  - sudo $TRAVIS_BUILD_DIR/deploy/travis/test.sh