language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: required

addons:
  apt:
    update: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install azure-cli

install:
  - make requirements

script:
  - .travis/test.sh