language: python

python:
  - "3.4"

virtualenv:
  system_site_packages: true

sudo: required

addons:
  apt:
    update: true

before_install:
  - sudo apt-get update -qq

install:
  - .travis/install.sh

before_script:
  - .travis/login.sh

script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - .travis/test.sh
  # Killing background sleep loop
  - kill %1