language: python
jdk: openjdk9
python: 3.4
sudo: required
virtualenv:
  system_site_packages: true
addons:
  apt:
    update: true

before_install:
  - sudo apt-get update -qq
  - mvn -f src/ clean install
# install:
#   - .travis/install.sh
# before_script:
#   - .travis/login.sh
# script:
#   - .travis/test.sh
  - .travis/test-alerts.sh